### ISSUE TITLE
Smart contracts not secure

### ISSUE THREAD

**Issue by smitrajput** [smitrajput/D-Crowdfund#2]

**Comment by Roelman** [comment]
Error: dlopen(/Users/r.mangal/D-Crowdfund/node_modules/scrypt/build/Release/scrypt.node, 1): no suitable image found.  Did find:
	/Users/r.mangal/D-Crowdfund/node_modules/scrypt/build/Release/scrypt.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/r.mangal/D-Crowdfund/node_modules/scrypt/build/Release/scrypt.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/r.mangal/D-Crowdfund/node_modules/scrypt/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Module._compile (/Users/r.mangal/D-Crowdfund/node_modules/next/node_modules/source-map-support/source-map-support.js:492:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)

**Comment by Roelman** [comment]
How do i resolve this?

**Comment by smitrajput** [comment]
Not sure how
